### ISSUE TITLE
can't compile with cplex 12.2

### ISSUE THREAD

**Issue by svigerske** [coin-or/Bcp#26]
Issue created by migration from Trac.

Original creator: compiler

Original creation time: 2011-10-04 17:44:32

Assignee: somebody

Version: 2.0

Hi,

I am using Mac OS X 10.6.8 (10K549) with gcc4.3 +gfortran (Not directly related to this problem but I could not compile the code with gcc45 and gcc46). As instructed in the configure.site file, I have declared the cplex include and library directories as follows:

with_cplex_incdir='/CPLEX/cplex/include/ilcplex'
with_cplex_lib='-L/CPLEX/cplex/lib/x86-64_darwin9_gcc4.0/static_pic -lcplex -lpthread'

It says it can't compile the simple test code that calls CPXgetstat. I don't think the problem is a cplex licence problem because the ILM file path is a global env var on my system. 

I couldn't attached the configure log, so here is a snapshot:

.....
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.16.0... yes
checking for COIN-OR package CoinUtils... yes: 2.8.1 
checking for COIN-OR package Glpk... not given: No package 'coinglpk' found
checking for COIN-OR package SoPlex... not given: No package 'coinsoplex' found
checking for COIN-OR package Sample... not given: No package 'coindatasample' found
checking for COIN-OR package Netlib... not given: No package 'coindatanetlib' found
checking if user provides library for Cplex... yes
checking whether symbol CPXgetstat is available with CPX... no
configure: error: Cannot find symbol(s) CPXgetstat with CPX
configure: error: /bin/sh '../../Osi/configure' failed for Osi

Thanks,
Serdar Karademir

**Comment by svigerske** [comment]
Comment by compiler created at 2011-10-16 01:08:42

i guess the reason is that cplex 12.2 compiles only with gcc4.0. If anyone could verify that, this ticket could be closed.

**Comment by svigerske** [comment]
Comment by artondorneles created at 2013-08-01 15:56:05

Replying to [ticket:26 compiler]:
> Hi,
> 
> I am using Mac OS X 10.6.8 (10K549) with gcc4.3 +gfortran (Not directly related to this problem but I could not compile the code with gcc45 and gcc46). As instructed in the configure.site file, I have declared the cplex include and library directories as follows:
> 
> with_cplex_incdir='/CPLEX/cplex/include/ilcplex'
> with_cplex_lib='-L/CPLEX/cplex/lib/x86-64_darwin9_gcc4.0/static_pic -lcplex -lpthread'
> 
> It says it can't compile the simple test code that calls CPXgetstat. I don't think the problem is a cplex licence problem because the ILM file path is a global env var on my system. 
> 
> I couldn't attached the configure log, so here is a snapshot:
> 
> .....
> checking for pkg-config... /opt/local/bin/pkg-config
> checking pkg-config is at least version 0.16.0... yes
> checking for COIN-OR package CoinUtils... yes: 2.8.1 
> checking for COIN-OR package Glpk... not given: No package 'coinglpk' found
> checking for COIN-OR package SoPlex... not given: No package 'coinsoplex' found
> checking for COIN-OR package Sample... not given: No package 'coindatasample' found
> checking for COIN-OR package Netlib... not given: No package 'coindatanetlib' found
> checking if user provides library for Cplex... yes
> checking whether symbol CPXgetstat is available with CPX... no
> configure: error: Cannot find symbol(s) CPXgetstat with CPX
> configure: error: /bin/sh '../../Osi/configure' failed for Osi
> 
> Thanks,
> Serdar Karademir

I guess you just need to append -lm after -lpthread.
