### ISSUE TITLE
stable/1.1 does not compile with gcc-4.4

### ISSUE THREAD

**Issue by svigerske** [coin-or/Bcp#22]
Issue created by migration from Trac.

Original creator: fmargot

Original creation time: 2009-06-17 08:18:41

Assignee: somebody

Version: 

CC:  fmargot@andrew.cmu.edu

When compiling CoinUtils from Bcp/stable/1.1 on a 64 bits machine with Fedora 11 and gcc version 4.4.0 20090506 (Red Hat 4.4.0-4) (GCC), I get:

../../../CoinUtils/src/CoinFactorization.hpp:725: error: there are no arguments to 'printf' that depend on a template parameter, so a declaration of 'printf' must be available ../../../CoinUtils/src/CoinFactorization.hpp:725: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)

The line in question is the printf() line in:
```
  if ( l + numberInPivotColumn > lengthAreaL_ ) {
    //need more memory
    printf("more memory needed in middle of invert\n");
    return false;
  }
```

After commenting out this printf line, there are additional errors that can be fixed by including stdio.h in file CoinUtils/CoinParamUtils.cpp.
